//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JINSHIN.Finance.AccountSystem {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class accounting {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal accounting() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JINSHIN.Finance.AccountSystem.accounting", typeof(accounting).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 69746686 的當地語系化字串。
        /// </summary>
        public static string accGovNo {
            get {
                return ResourceManager.GetString("accGovNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發票掃描-金心資訊 的當地語系化字串。
        /// </summary>
        public static string accInvText {
            get {
                return ResourceManager.GetString("accInvText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 107 的當地語系化字串。
        /// </summary>
        public static string accYear {
            get {
                return ResourceManager.GetString("accYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請再設定資料 的當地語系化字串。
        /// </summary>
        public static string AffairsMsg01 {
            get {
                return ResourceManager.GetString("AffairsMsg01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 C:\金心資訊財務報稅系統 的當地語系化字串。
        /// </summary>
        public static string ClickPath {
            get {
                return ResourceManager.GetString("ClickPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ©金心資訊科技有限公司 的當地語系化字串。
        /// </summary>
        public static string FormDataTitle {
            get {
                return ResourceManager.GetString("FormDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 10000 的當地語系化字串。
        /// </summary>
        public static string MsgTime {
            get {
                return ResourceManager.GetString("MsgTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 -餐廳收入 的當地語系化字串。
        /// </summary>
        public static string RestACCDesc {
            get {
                return ResourceManager.GetString("RestACCDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 1113 的當地語系化字串。
        /// </summary>
        public static string RestACCIDGet {
            get {
                return ResourceManager.GetString("RestACCIDGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 4111 的當地語系化字串。
        /// </summary>
        public static string RestACCIDLend {
            get {
                return ResourceManager.GetString("RestACCIDLend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 訂單:{0} 金額:{1}  儲存完成 的當地語系化字串。
        /// </summary>
        public static string RestMsg {
            get {
                return ResourceManager.GetString("RestMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 FinanceSrvAdr 的當地語系化字串。
        /// </summary>
        public static string SrvDataName {
            get {
                return ResourceManager.GetString("SrvDataName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 6123 的當地語系化字串。
        /// </summary>
        public static string TaxACCID {
            get {
                return ResourceManager.GetString("TaxACCID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 稅捐 的當地語系化字串。
        /// </summary>
        public static string TaxDesc {
            get {
                return ResourceManager.GetString("TaxDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 0 的當地語系化字串。
        /// </summary>
        public static string TrailSys {
            get {
                return ResourceManager.GetString("TrailSys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 1 的當地語系化字串。
        /// </summary>
        public static string TrailVerify {
            get {
                return ResourceManager.GetString("TrailVerify", resourceCulture);
            }
        }
    }
}
