//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JINSHIN.Finance.AccountSystem {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FormCaption {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormCaption() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JINSHIN.Finance.AccountSystem.FormCaption", typeof(FormCaption).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 請填寫完整的類別、名稱、數量、金額 的當地語系化字串。
        /// </summary>
        public static string AccProductMsg001 {
            get {
                return ResourceManager.GetString("AccProductMsg001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 事務明細資料確認新增 的當地語系化字串。
        /// </summary>
        public static string AffairsDetailCaption01 {
            get {
                return ResourceManager.GetString("AffairsDetailCaption01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 事務資料確認新增 的當地語系化字串。
        /// </summary>
        public static string AffairsMasterCaption01 {
            get {
                return ResourceManager.GetString("AffairsMasterCaption01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 財產資料確認新增 的當地語系化字串。
        /// </summary>
        public static string AssetsMasterCaption01 {
            get {
                return ResourceManager.GetString("AssetsMasterCaption01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇資料更新 的當地語系化字串。
        /// </summary>
        public static string BookAffairsAccountCaption01 {
            get {
                return ResourceManager.GetString("BookAffairsAccountCaption01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇資料刪除 的當地語系化字串。
        /// </summary>
        public static string BookAffairsAccountCaption02 {
            get {
                return ResourceManager.GetString("BookAffairsAccountCaption02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請輸人新增資料 的當地語系化字串。
        /// </summary>
        public static string BookAffairsAccountCaption03 {
            get {
                return ResourceManager.GetString("BookAffairsAccountCaption03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 子明細仍有資料 的當地語系化字串。
        /// </summary>
        public static string BookAffairsCaption01 {
            get {
                return ResourceManager.GetString("BookAffairsCaption01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 沒有資料 的當地語系化字串。
        /// </summary>
        public static string BookConvertCpation01 {
            get {
                return ResourceManager.GetString("BookConvertCpation01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料完全正確 的當地語系化字串。
        /// </summary>
        public static string BookConvertCpation02 {
            get {
                return ResourceManager.GetString("BookConvertCpation02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 有相同的資料 的當地語系化字串。
        /// </summary>
        public static string BookDescCaption01 {
            get {
                return ResourceManager.GetString("BookDescCaption01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料尚未新增 的當地語系化字串。
        /// </summary>
        public static string BookDescCaption02 {
            get {
                return ResourceManager.GetString("BookDescCaption02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 尚未填寫完整的資料 的當地語系化字串。
        /// </summary>
        public static string BookDescCaption03 {
            get {
                return ResourceManager.GetString("BookDescCaption03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 尚未選擇查詢條件 的當地語系化字串。
        /// </summary>
        public static string BookDiaryCatpion01 {
            get {
                return ResourceManager.GetString("BookDiaryCatpion01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請先按查詢 的當地語系化字串。
        /// </summary>
        public static string IncomeReport001 {
            get {
                return ResourceManager.GetString("IncomeReport001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 帳號已被鎖定 的當地語系化字串。
        /// </summary>
        public static string LoginLock {
            get {
                return ResourceManager.GetString("LoginLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 帳號存在，帳號密碼錯誤?  的當地語系化字串。
        /// </summary>
        public static string LoginMsg {
            get {
                return ResourceManager.GetString("LoginMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 帳號密碼發生問題，請聯絡金心資訊 的當地語系化字串。
        /// </summary>
        public static string LoginServerLock {
            get {
                return ResourceManager.GetString("LoginServerLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 廠商資料不符合，檢查廠商名稱 的當地語系化字串。
        /// </summary>
        public static string NoCompanyMsg {
            get {
                return ResourceManager.GetString("NoCompanyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 s8xiek2@ 的當地語系化字串。
        /// </summary>
        public static string Pass {
            get {
                return ResourceManager.GetString("Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 帳號存在，統一編號、廠商鍵值、廠商名稱輸人不完整，請確認 的當地語系化字串。
        /// </summary>
        public static string RegInputError01 {
            get {
                return ResourceManager.GetString("RegInputError01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 統一編號、廠商鍵值重覆、廠商名稱輸人不一致，請確認 的當地語系化字串。
        /// </summary>
        public static string RegInputError02 {
            get {
                return ResourceManager.GetString("RegInputError02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請輸入不同的使用者帳號、完整的姓名 的當地語系化字串。
        /// </summary>
        public static string RegInputError03 {
            get {
                return ResourceManager.GetString("RegInputError03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 第一次使用請註冊，取得帳號密碼 的當地語系化字串。
        /// </summary>
        public static string RegMsg {
            get {
                return ResourceManager.GetString("RegMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 有註冊序號問題,請聯絡金心資訊 的當地語系化字串。
        /// </summary>
        public static string RegSNCheck {
            get {
                return ResourceManager.GetString("RegSNCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請先產生序號 的當地語系化字串。
        /// </summary>
        public static string RegUserMsg001 {
            get {
                return ResourceManager.GetString("RegUserMsg001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 帳號的擁有人不是你 的當地語系化字串。
        /// </summary>
        public static string RegUserMsg002 {
            get {
                return ResourceManager.GetString("RegUserMsg002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 帳號存在、廠商資料不符合，檢查廠商鍵值及資料 的當地語系化字串。
        /// </summary>
        public static string RegUserMsg003 {
            get {
                return ResourceManager.GetString("RegUserMsg003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 帳號存在，廠商資料不符合，檢查廠商名稱 的當地語系化字串。
        /// </summary>
        public static string RegUserMsg005 {
            get {
                return ResourceManager.GetString("RegUserMsg005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 帳號不存在、廠商資料不符合，檢查廠商鍵值及資料 的當地語系化字串。
        /// </summary>
        public static string RegUserMsg006 {
            get {
                return ResourceManager.GetString("RegUserMsg006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 帳號存在，統一編號有誤 的當地語系化字串。
        /// </summary>
        public static string RegUserMsg007 {
            get {
                return ResourceManager.GetString("RegUserMsg007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 帳號存在，請核對個人資料及姓名 的當地語系化字串。
        /// </summary>
        public static string RegUserMsg008 {
            get {
                return ResourceManager.GetString("RegUserMsg008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請勾選同意以上條款 的當地語系化字串。
        /// </summary>
        public static string SNAgree {
            get {
                return ResourceManager.GetString("SNAgree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請填寫 （鍵值 ) 的當地語系化字串。
        /// </summary>
        public static string SNKey {
            get {
                return ResourceManager.GetString("SNKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 更動了使用者帳號，請再取序號 的當地語系化字串。
        /// </summary>
        public static string UpdateServerAgain {
            get {
                return ResourceManager.GetString("UpdateServerAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Finance06 的當地語系化字串。
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已有相同的使用者名稱 的當地語系化字串。
        /// </summary>
        public static string UserNameTheSame {
            get {
                return ResourceManager.GetString("UserNameTheSame", resourceCulture);
            }
        }
    }
}
