//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JINSHIN.Finance.AccountSystem.Resources {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    public sealed partial class Diary : global::System.Configuration.ApplicationSettingsBase {
        
        private static Diary defaultInstance = ((Diary)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Diary())));
        
        public static Diary Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("299")]
        public string Office365 {
            get {
                return ((string)(this["Office365"]));
            }
            set {
                this["Office365"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("31937")]
        public string Salary {
            get {
                return ((string)(this["Salary"]));
            }
            set {
                this["Salary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2328")]
        public string CompanyInsurace {
            get {
                return ((string)(this["CompanyInsurace"]));
            }
            set {
                this["CompanyInsurace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2474")]
        public string LaborHealthInsuranceCost {
            get {
                return ((string)(this["LaborHealthInsuranceCost"]));
            }
            set {
                this["LaborHealthInsuranceCost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public string OfficeCost {
            get {
                return ((string)(this["OfficeCost"]));
            }
            set {
                this["OfficeCost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WF")]
        public string DiaryAccNo {
            get {
                return ((string)(this["DiaryAccNo"]));
            }
            set {
                this["DiaryAccNo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("775")]
        public string MediaCost {
            get {
                return ((string)(this["MediaCost"]));
            }
            set {
                this["MediaCost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WF")]
        public string AccNo {
            get {
                return ((string)(this["AccNo"]));
            }
            set {
                this["AccNo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public string AccNoNum {
            get {
                return ((string)(this["AccNoNum"]));
            }
            set {
                this["AccNoNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("yyyyMMdd")]
        public string AccNoDate {
            get {
                return ((string)(this["AccNoDate"]));
            }
            set {
                this["AccNoDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2020")]
        public string AccYear {
            get {
                return ((string)(this["AccYear"]));
            }
            set {
                this["AccYear"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("金心資訊科技有限公司")]
        public string ReportTitle {
            get {
                return ((string)(this["ReportTitle"]));
            }
            set {
                this["ReportTitle"] = value;
            }
        }
    }
}
